/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215706;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

class MemoTest {
    
    @Test
    void memoTest() {
        try{
            TreeSet<Integer> memoTestResult5_4 = new TreeSet<Integer>();
            memoTestResult5_4.add(3);
            Sudoku sudokuTest = new Sudoku(9, 8, 1, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 7, 9, 2, 5, 0, 0, 7, 0, 1, 0, 6, 0, 8, 3, 0, 9, 0, 4, 0, 7, 5, 0, 2, 0, 0, 8, 0, 1, 0, 7, 0, 0, 7, 0, 3, 6, 0, 5, 0, 1, 0, 3, 1, 0, 7, 0, 4, 0, 9, 0, 0, 6, 9, 2, 3, 0, 0, 0, 0, 0, 5, 0, 9, 0, 0, 3, 2, 4);
            Memo memoTest = new Memo();
            memoTest.memo(sudokuTest.getSudoku());
            TreeSet<Integer> memoTest5_4 = new TreeSet<Integer>();
            memoTest5_4 = memoTest.getMemo5_4();
            assertEquals(memoTestResult5_4, memoTest5_4);
        }catch (Exception e){
            System.out.println("エラー発生！0~9の数字を入力してください。");
        }
    }
    
}